const actionTypes = {
    HEADER_INIT_DATA: 'HEADER_INIT_DATA',//清空数据--- 初始化数据
    HEADER_CHANGE_TITLE: 'HEADER_CHANGE_TITLE',//改变标题
    HEADER_CHAGNE_LESSON_DETAIL: 'HEADER_CHAGNE_LESSON_DETAIL',//改变学习要点
    HEADER_CHAGNE_COURSEWARE: 'HEADER_CHAGNE_COURSEWARE',//课程数组改变
};

export default actionTypes;